name: aspectratio
favicon: null
layout_spectrum: 0.36348
typography_spectrum: 0.39233
title: A dream becoming a reality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#3B3B39'
    - '#ED7709'
    - '#7ACEF2'
    - '#6D6D6B'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
