analytics: {}
color:
  brandColors:
    - '#070506'
    - '#322C30'
    - '#66798A'
    - '#BABCBB'
    - '#FEFEFE'
  brandStrength: 0.6875
  lightness: 0.8125
  rhythmicContrast: 0.25
  saturation: 0.1875
cta: {}
layout_spectrum: 0
name: aspectratio
opengraph: {}
purpose: []
typography_spectrum: 0.56299
