analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#3B3B39'
    - '#ED7709'
    - '#7ACEF2'
    - '#6D6D6B'
  brandStrength: 0.6875
  lightness: 0.1875
  rhythmicContrast: 0.25
  saturation: 0.25
cta: {}
layout_spectrum: 0
name: aspectratio
opengraph: {}
purpose: []
title: A dream becoming a reality
typography_spectrum: 0.39233
