name: aspectratio
favicon: null
layout_spectrum: 0.5922455319669098
typography_spectrum: 0.56299
title: A story about bringing a dream to reality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070506'
    - '#322c30'
    - '#66798a'
    - '#babcbb'
    - '#fefefe'
  brandStrength: 0
  lightness: 0.29191613709554076
  saturation: 0.24476799881085753
  rhythmicContrast: 0.2155383126810193
purpose: []
